language: php

php:
  - 7.0
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm  

before_script:
  - composer install --prefer-source --no-interaction

script: phpunit --configuration .phpunit.xml --coverage-text